export default {
  content: {
    readonly: false,
    removeButtons: [
      'source',
      'font',
      'brush',
      'copyformat',
      'symbol',
      'fullsize',
      'print',
      'about',
      'eraser',
    ],
  },
  excerpt: {
    readonly: false,
    removeButtons: [
      'source',
      'font',
      'brush',
      'copyformat',
      'symbol',
      'fullsize',
      'print',
      'about',
      'eraser',
      'fontsize',
      'paragraph',
      'file',
      'left',
      'right',
      'center',
      'justify',
      'superscript',
      'subscript',
      'strikethrough',
      'paste',
      'copy',
      'cut',
      'selectall',
      'break',
    ],
  },
  comment: {
    readonly: false,
    removeButtons: [
      'source',
      'font',
      'brush',
      'copyformat',
      'symbol',
      'fullsize',
      'print',
      'about',
      'eraser',
      'fontsize',
      'paragraph',
      'file',
      'left',
      'right',
      'center',
      'justify',
      'superscript',
      'subscript',
      'strikethrough',
      'paste',
      'copy',
      'cut',
      'selectall',
      'break',
    ],
  },
  chat: {
    readonly: false,
    removeButtons: [
      'source',
      'font',
      'brush',
      'copyformat',
      'symbol',
      'fullsize',
      'print',
      'about',
      'eraser',
      'fontsize',
      'paragraph',
      'file',
      'left',
      'right',
      'center',
      'justify',
      'superscript',
      'subscript',
      'strikethrough',
      'paste',
      'copy',
      'cut',
      'selectall',
      'break',
    ],
  },
}
